### ISSUE TITLE
Stock script returns "Not a valid stock symbol"

### ISSUE THREAD

**Issue by mathtd** [alexanderepstein/Bash-Snippets#211] opened 2020-01-08 16:31 UTC
**Issue Label:**
* [x] Bug
* [ ] New feature
* [ ] Enhancement
* [ ] New component

**Description:**
Looking for the price of AAPL returns "Not a valid stock symbol"
```
stocks AAPL
AAPL: Not a valid stock symbol
```

### If its a bug make sure to include this section.
**OS and OS version:**
* [X] Mac
* [ ] Linux 32 Bit
* [ ] Linux 64 Bit
* [ ] Windows 32 Bit
* [ ] Windows 64 Bit

OS Version: macOS Catalina 10.15.2

**Comment by alexanderepstein** [comment] 2020-01-08 17:18
Are you running version 1.23.0 try running `stocks -u`

**Comment by mathtd** [comment] 2020-01-08 18:03
Yes 1.23.0. 

```
stocks -u AAPL
Bash-Snippets is already the latest version
```

If I run `bash -x stocks AAPL` it seems that the problem comes from:

```
++ curl -A curl -s https://financialmodellingprep.com/api/v3/company/profile/AAPL
+ stockProfile='<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/1.14.0 (Ubuntu)</center>
</body>
'/html>
```

**Comment by mountaineerbr** [comment] 2020-01-08 19:02
Try 'curl -sL ..'

**Comment by mathtd** [comment] 2020-01-08 19:22
That works!

**Comment by alexanderepstein** [comment] 2020-01-08 23:28
So it seems the endpoint must have changed, will update the Stocks component with the new endpoint

**Comment by alexanderepstein** [comment] 2020-01-09 07:21
Seems like they changed the URL from https://financialmodellingprep.com -> https://financialmodelingprep.com, I pushed a fix in bb561e5048d07b6709192896b37fef32059da16f and will release an update soon. Thanks for making me aware of the issue! If you want the changes now, you can rerun the git install steps and skip the step of checking out to the latest stable build.

**Closed by alexanderepstein** 2020-01-09 07:21 UTC

**Comment by mathtd** [comment] 2020-01-09 15:41
Great, thank you!

**Comment by typebrook** [comment] 2020-02-13 12:12
@alexanderepstein 
`stock` fails again, should reopen this issue

I think this is caused by request header, for short
```
