### ISSUE TITLE
qrify doesn't seem to work right on osx

### ISSUE THREAD

**Issue by gdoteof** [alexanderepstein/Bash-Snippets#57] opened 2017-07-14 14:08 UTC
**Issue Label:**
* [x] Bug
* [ ] New feature
* [ ] Enhancement
* [ ] New component

**Description:**
qrify has unexpected spacing

![image](https://user-images.githubusercontent.com/151115/28215503-492b680a-687c-11e7-975c-a6b21f074993.png)

### If its a bug make sure to include this section.
**OS and OS version:**
* [x] Mac
* [ ] Linux 32 Bit
* [ ] Linux 64 Bit
* [ ] Windows 32 Bit
* [ ] Windows 64 Bit

OS Version: 10.12.1

**Comment by alexanderepstein** [comment] 2017-07-14 14:13
What terminal are you using? 

I personally have tested this on iTerm2 on OSX. The spacing is definitely an interesting bug and sadly renders the qrcode to be unreadable.

@chubin just making you aware of this in case it is a bug with qrenco

**Comment by gdoteof** [comment] 2017-07-14 14:16
This is iTerm2.

![image](https://user-images.githubusercontent.com/151115/28215818-550f20d4-687d-11e7-9690-70e40f19ff8a.png)

I don't believe I have changed any of the settings, but it's possible.

**Comment by gdoteof** [comment] 2017-07-14 14:17
fwiw, it works much better in 'Terminal'

![image](https://user-images.githubusercontent.com/151115/28215926-a8feaeb2-687d-11e7-99ff-ed8f9152610e.png)

**Comment by chubin** [comment] 2017-07-14 14:23
It's not a bug actually, it's a feature, at least it's known that there are fonts that can't be used for QR-code generation. You can't do anything with it. The only possible solution (and that is only for iterm2) to generate a PNG to show it (like here: https://www.iterm2.com/documentation-images.html ). Could it be the solution for you? If yes, we could implement it.

**Comment by gdoteof** [comment] 2017-07-14 14:26
Yes it would be a fine a solution.  It would also be acceptable to note which font(s) is/are recommended; especially if other bits that use ascii art are also limited in their fidelity by my font choice (which I am not attached to at all)

**Comment by chubin** [comment] 2017-07-14 14:37
@gdoteof Does curl wttr.in work for you like it should? Or does it also look ugly?

**Comment by gdoteof** [comment] 2017-07-14 14:40
it looks okay to me, slightly less good in iTerm2 (top) than Terminal (bottom)

![image](https://user-images.githubusercontent.com/151115/28216787-d52b2ac6-6880-11e7-9c9e-8d2357cb2436.png)

**Comment by chubin** [comment] 2017-07-14 14:46
Ok, that means that the only possible solution is to use PNG-based QR-codes (but keep in mind that they will work only in iTerm2).

Have you tried to change line spacing by the way?

https://apple.stackexchange.com/questions/198518/how-to-make-font-size-equal-to-15-in-terminal-on-mac-os-x-yosemite

**Comment by gdoteof** [comment] 2017-07-14 14:53
I just tried a bit, not really great results.  What font are you using that works so nicely?

![image](https://user-images.githubusercontent.com/151115/28217274-95db4e58-6882-11e7-97f3-e02a2f41524e.png)

**Comment by chubin** [comment] 2017-07-14 14:58
I don't use Mac OS X, and in Linux, I tested it in many terminals, and it looks nice everywhere.
Unfortunately, I have no Mac at hand to see how it works there. 
Does it work for you in the browser? Just open qrenco.de in it.

**Comment by gdoteof** [comment] 2017-07-14 15:05
nah kinda looks like crap here too

![image](https://user-images.githubusercontent.com/151115/28217783-4fb117ee-6884-11e7-990f-eeaff2383a8d.png)

**Comment by chubin** [comment] 2017-07-14 15:08
Strange, it works well on my iPhone (it would be great if someone could it test it on some other Mac OS X hosts)

**Comment by linyostorovovoltos** [comment] 2017-07-14 15:43
I just checked on a Mac, although I normally use Linux, and can confirm that it does look like crap on Chrome and Safari, although it seems to appear to work correctly in Firefox. In normal Terminal, it appears to look fine and work fine, albeit not looking the best.

**Comment by chubin** [comment] 2017-07-14 15:46
@linyostorovovoltos Thank you for the help! What about iTerm2?

**Comment by linyostorovovoltos** [comment] 2017-07-14 15:47
@chubin I don't currently have iTerm2 installed, I'm going to get that up and running soon enough.

**Comment by chubin** [comment] 2017-07-14 15:48
@linyostorovovoltos Thank you very much! Could you please also post here how it looks like in your default terminal? I just want to understand it better (and it works for you as I can understand; that means that you can scan the QR-code with your smartphone)

**Comment by linyostorovovoltos** [comment] 2017-07-14 16:03
The iTerm does come out as bad looking and not working.
Right now GitHub isn't letting me upload the screenshots (?) :( Sorry for being unhelpful.

**Comment by linyostorovovoltos** [comment] 2017-07-14 16:07
iTerm2, and it works in normal Terminal. Here are the screenshots now: 
![screen shot 2017-07-14 at 11 49 27 am](https://user-images.githubusercontent.com/24398526/28220305-f17b459c-688c-11e7-9710-56a8919fbbcb.png)
iTerm2 ^
![screen shot 2017-07-14 at 11 54 34 am](https://user-images.githubusercontent.com/24398526/28220311-f9d64bce-688c-11e7-9c25-c9dbc0a1ed1e.png)
Default ^

**Comment by linyostorovovoltos** [comment] 2017-07-14 16:08
Ok, now I feel bad, since the iterm2 actually does work!

**Comment by chubin** [comment] 2017-07-14 16:10
It probably depends on the smartphone, not every smartphone can read such QR-codes I suppose

**Comment by linyostorovovoltos** [comment] 2017-07-14 16:11
In fact, any QR reader I put any of the codes into works.

**Comment by alexanderepstein** [comment] 2017-07-14 17:41
Is ```imgcat``` native to iTerm2? If it isn't I am not sure if i want to implement the ability to get the qrcode as a png as I am doing my best to stay away from external dependencies.

**Comment by gdoteof** [comment] 2017-07-14 20:40
i don't believe it is.  i was actually able to read these using my phone after a few tries

**Comment by alexanderepstein** [comment] 2017-07-15 18:41
Okay, going to close this issue only because it seems to be working now and the only viable solution to fix the issue would be to generate pngs which i do not want to implement because of the dependency

**Closed by alexanderepstein** 2017-07-15 18:41 UTC
Labels: Accepted, Bug
